export const links: { name: string; category: string }[] = [
  { name: "The Muslim Lantern", category: "Dawah" },
  { name: "One Message Foundation", category: "Dawah" },
  { name: "One Path Network", category: "Dawah" },
  { name: "Talk Islam", category: "Dawah" },
  { name: "Merciful Servant", category: "Dawah" },
  { name: "Elzero Web School", category: "Coding" },
  { name: "عبدالله العلاوي", category: "Influencers" },
  { name: "Mohammed Besar", category: "Coding" },
  { name: "Yasser Mamdouh", category: "Dawah" },
  { name: "عمر عبد الكافي", category: "Dawah" },
  { name: "Codevolution", category: "Coding" },
  { name: "وزارة الدفاع العقدي", category: "Dawah" },
  { name: "الدكتور إياد قنيبي - القناة الرسمية", category: "Dawah" },
  { name: "Blogging Theology", category: "Dawah" },
  { name: "The Muslim Skeptic", category: "Dawah" },
  { name: "Codezilla", category: "Coding" },
  { name: "One True Message Foundation", category: "Dawah" },
  { name: "TheDeenShowTV", category: "Dawah" },
  { name: "محمد غنايم", category: "Influencers" },
  { name: "Amigoscode", category: "Coding" },
  { name: "سليمان بن خالد | solyman_95", category: "Dawah" },
  { name: "أنس الشافعي", category: "Quran" },
  { name: "Fatih Seferagic", category: "Quran" },
  { name: "OctuCode", category: "Coding" },
  { name: "EFDawah", category: "Dawah" },
  { name: "The Muslim Metaphysician", category: "Dawah" },
  { name: "قناة زين خير الله", category: "Dawah" },
  { name: "Dr. Hazem Shouman", category: "Dawah" },
  { name: "Dr. Othman Alkamees - الشيخ الدكتور عثمان الخميس", category: "Dawah" },
  { name: "Mufti Menk", category: "Dawah" },
  { name: "Islam Sobhi | القارئ اسلام صبحي", category: "Quran" },
  { name: "iERAOrg", category: "Dawah" },
  { name: "Sapience Institute", category: "Dawah" },
  { name: "القناة الرسمية للشيخ منصور السالمي", category: "Quran" },
  { name: "القارئ علي عبدالسلام اليوسف", category: "Quran" },
  { name: "Ahmad alnufais | أحمد النفيس", category: "Quran" },
  { name: "عبدالعزيز سحيم | Abdelaziz Sheim", category: "Quran" },
];
